# Week 2 - Mini Assessment

Welcome to your mini assessment for week two. A set of exercises using NumPy to make sure you get accustomed to one of the most widely used libraries in the data analytics/science community.

Once you are done with the notebook, you should try to put it on GitHub under your respective folder for everything related to module 2. In addition let your instructor know that you have submitted this mini-assessment.

1. Import the numpy package and check its version.

In [1]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

2. Create an numpy range of values from 0 to 49 and name it `mynums`. Print its output.

In [5]:
mynums = np.arange(0,50)
mynums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

3. Reshape the array you created in step 2 into a matrix with the shape below and assign a copy of it to a variable called `my_matrix`. Print the matrix.

In [8]:
my_matrix = mynums.reshape(5,10)
my_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

4. Create a linearly-spaced array of size 100 between the numbers 20 to 100, assign it to the variable, `num_increases` and print it.

In [9]:
num_increases = np.linspace(20,100,num=100)
num_increases

array([ 20.        ,  20.80808081,  21.61616162,  22.42424242,
        23.23232323,  24.04040404,  24.84848485,  25.65656566,
        26.46464646,  27.27272727,  28.08080808,  28.88888889,
        29.6969697 ,  30.50505051,  31.31313131,  32.12121212,
        32.92929293,  33.73737374,  34.54545455,  35.35353535,
        36.16161616,  36.96969697,  37.77777778,  38.58585859,
        39.39393939,  40.2020202 ,  41.01010101,  41.81818182,
        42.62626263,  43.43434343,  44.24242424,  45.05050505,
        45.85858586,  46.66666667,  47.47474747,  48.28282828,
        49.09090909,  49.8989899 ,  50.70707071,  51.51515152,
        52.32323232,  53.13131313,  53.93939394,  54.74747475,
        55.55555556,  56.36363636,  57.17171717,  57.97979798,
        58.78787879,  59.5959596 ,  60.4040404 ,  61.21212121,
        62.02020202,  62.82828283,  63.63636364,  64.44444444,
        65.25252525,  66.06060606,  66.86868687,  67.67676768,
        68.48484848,  69.29292929,  70.1010101 ,  70.90

array([ 20.        ,  20.80808081,  21.61616162,  22.42424242,
        23.23232323,  24.04040404,  24.84848485,  25.65656566,
        26.46464646,  27.27272727,  28.08080808,  28.88888889,
        29.6969697 ,  30.50505051,  31.31313131,  32.12121212,
        32.92929293,  33.73737374,  34.54545455,  35.35353535,
        36.16161616,  36.96969697,  37.77777778,  38.58585859,
        39.39393939,  40.2020202 ,  41.01010101,  41.81818182,
        42.62626263,  43.43434343,  44.24242424,  45.05050505,
        45.85858586,  46.66666667,  47.47474747,  48.28282828,
        49.09090909,  49.8989899 ,  50.70707071,  51.51515152,
        52.32323232,  53.13131313,  53.93939394,  54.74747475,
        55.55555556,  56.36363636,  57.17171717,  57.97979798,
        58.78787879,  59.5959596 ,  60.4040404 ,  61.21212121,
        62.02020202,  62.82828283,  63.63636364,  64.44444444,
        65.25252525,  66.06060606,  66.86868687,  67.67676768,
        68.48484848,  69.29292929,  70.1010101 ,  70.90

5. Create an numpy array with 20 zeros, assign it to the variable `zeroes`.

In [11]:
zeroes = np.zeros(20)
zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

6. Create a two dimensional array of size 7 by 8 filled with 1s and do the following:
- mulptiply the first rows by 2
- add 3, and raise to the power of two the odd columns starting from the beginning
- subtract 10 and multiply by 15 the elements in the even rows and odd columns

In [12]:
ones = np.ones((7,8))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
ones[0,:]*2

array([2., 2., 2., 2., 2., 2., 2., 2.])

In [16]:
(ones[:,::2] + 3)**2

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

In [18]:
(ones[::2,1::2] - 10)*15

array([[-135., -135., -135., -135.],
       [-135., -135., -135., -135.],
       [-135., -135., -135., -135.],
       [-135., -135., -135., -135.]])

array([[-135., -135., -135., -135.],
       [-135., -135., -135., -135.],
       [-135., -135., -135., -135.],
       [-135., -135., -135., -135.]])

7. Create a numpy array starting at 20 and ending at 40 with 10 equally spaced values. Print your result.

In [20]:
equalspace = np.linspace(20,40,num=10)
equalspace

array([20.        , 22.22222222, 24.44444444, 26.66666667, 28.88888889,
       31.11111111, 33.33333333, 35.55555556, 37.77777778, 40.        ])

array([20.        , 22.22222222, 24.44444444, 26.66666667, 28.88888889,
       31.11111111, 33.33333333, 35.55555556, 37.77777778, 40.        ])

8. Create a 9 by 9 matrix with random integers from 100 to 500 and use the dtype "int32".

In [31]:
newmatrix = np.random.randint(100,500,size=(9,9),dtype='int32')
print(newmatrix)
newmatrix.dtype

[[426 276 312 440 465 118 375 281 266]
 [161 204 474 248 102 329 407 412 361]
 [117 439 197 437 262 344 279 447 252]
 [465 324 191 166 346 135 266 287 185]
 [125 343 483 420 266 236 379 379 452]
 [354 239 230 342 394 465 358 235 417]
 [481 479 267 265 186 225 471 221 373]
 [472 261 455 168 187 257 198 415 478]
 [254 199 171 323 441 490 429 466 345]]


dtype('int32')

array([[318, 168, 216, 178, 198, 380, 149, 365, 350],
       [225, 425, 491, 156, 301, 300, 245, 285, 273],
       [214, 225, 449, 421, 256, 444, 376, 233, 482],
       [344, 396, 280, 460, 386, 318, 131, 350, 490],
       [415, 137, 330, 206, 288, 444, 399, 459, 476],
       [244, 152, 375, 211, 116, 216, 397, 120, 201],
       [213, 498, 498, 270, 182, 242, 357, 262, 396],
       [387, 445, 266, 280, 354, 360, 356, 426, 286],
       [210, 365, 118, 269, 101, 364, 320, 484, 298]], dtype=int32)

9. Create an empty array of 20 elements with shape 2 by 10, dtype 'float32' and add a different number to each row.

In [37]:
newmatrix2 = np.empty((2,10), dtype='float32')
newmatrix2

array([[ 0.00000000e+00,  2.81250000e+00, -2.27893146e-30,
         2.84722209e+00,  7.99975539e-22,  2.88194442e+00,
        -3.03164910e-13,  2.91666651e+00,  1.08506945e-04,
         2.95138884e+00],
       [-4.00497773e+04,  2.98611093e+00, -3.03164910e-13,
         3.01041651e+00,  1.97190097e+30,  3.02777767e+00,
         1.08506945e-04,  3.04513884e+00,  0.00000000e+00,
         3.06250000e+00]], dtype=float32)

array([[-2.68156159e+154,  1.49457291e-154,  6.93271142e-310,
         6.93271155e-310,  6.93271142e-310,  6.93271155e-310,
         6.93271155e-310,  6.93271155e-310,  6.93271155e-310,
         6.93271155e-310],
       [ 6.93271155e-310,  6.93271155e-310,  6.93271142e-310,
         6.93271155e-310,  6.93271142e-310,  6.93271155e-310,
         1.49457291e-154, -2.68678346e+154,  6.01346953e-154,
         1.39067116e-308]])

In [38]:
newmatrix2[0,:]=4
newmatrix2[1,:]=-3
newmatrix2

array([[ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3., -3.]], dtype=float32)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[-5. -5. -5. -5. -5. -5. -5. -5. -5. -5.]


10. Create an array with 15 random numbers between 100 and 200 and print the maximum value of the array.

In [40]:
newmatrix3 = np.random.randint(100,200, size=15)
newmatrix3

array([138, 178, 101, 194, 185, 195, 174, 113, 119, 140, 154, 164, 157,
       152, 160])

In [41]:
np.max(newmatrix3)

195

11. Create an array with the following numbers [40, 41, 26, 14, 15, 47, 43, 33, 44, 22], and assign it to a variable
- create a slice from the 5th to 10th element, and assign it to a variable
- change the value of both arrays with any operation you'd like (add, subtract, multiply, etc.), and 
- then print all 3 (the first array and your next two variables).

In [43]:
newarray = np.array([40, 41, 26, 14, 15, 47, 43, 33, 44, 22])
newarray

array([40, 41, 26, 14, 15, 47, 43, 33, 44, 22])

In [44]:
newslice = newarray[4:]
newslice

array([15, 47, 43, 33, 44, 22])

In [45]:
newslice*4

array([ 60, 188, 172, 132, 176,  88])

In [46]:
newarray

array([40, 41, 26, 14, 15, 47, 43, 33, 44, 22])

In [48]:
newarray2 = newarray.copy()**2
newarray2

array([1600, 1681,  676,  196,  225, 2209, 1849, 1089, 1936,  484],
      dtype=int32)

12. Create an array of 360 random numbers from -10 to 50 (to resemble the weather) and find the min, max, 25th percentile, 75 percentile, average, and the median.

In [49]:
weather = np.random.randint(-10,50,size=360)
weather

array([ -3,  18,  35,   3,  29, -10,  44,  35,   2,  39,  21,  14,   1,
         7,  40,  35,  30,  42,  39,  11,  21,  14,  43,  -9,  40,  21,
        37,  46,  47,   8,  -7,  36,  14,  45,   2,  30,  30,  -6,  43,
        23,  48,  28,  45,  26, -10,   5,  23,   7,   1,  47,  45,   6,
        37,  29,  13,  31,  28,  11,  38,  -4,  -8,  47,   4,  -2,   3,
         4,  30,  23,  22,  -7,  39,  26,  12,  36,  -2,  43,  34,   3,
        -4,  -7,  35,  38,  44,  14,  -7,   9,  21,  32,   6,  -6,  -3,
        13,  12,  15,  15,  -6,  27,  24,  45,  -5,  -1,  21,  -7,  11,
        42,   7,  11,  11,   4,  -8,  -1,  46,  23,  21,  29,   6,  -3,
        22,  29,   0,  12,  29,  36,   1,   6,  19,   8,  15,  -7,  15,
         3,  -1,  -9,  46,  11,  24,   0,  45,  10,  32,  49,  -9,  48,
        14,  18,  10, -10,   3,  -8,  -4,  49,  27,  30,   3,  39,  11,
        12,  46,   4,  35,  41,  17,  39,  26,  29,  -9,  49,  29,  10,
        39,  47,   6,  13,  34,  24,  42,  28,  38,   8,  34,  3

In [65]:
print(f"min:{np.min(weather)}")
print(f"max:{np.max(weather)}")
print(f"25th percentile:{np.percentile(weather,25)}")
print(f"75th percentile:{np.percentile(weather,75)}")
print(f"average:{np.mean(weather)}")
print(f"median:{np.median(weather)}")

min:-10
max:49
25th percentile:4.0
75th percentile:34.0
average:19.658333333333335
median:21.0


13. Reshape the array you created in step 12 into a matrix of 30 by 12 and get the same values but only for the months this time.

In [59]:
newweather = weather.reshape(12,30)
newweather

array([[ -3,  18,  35,   3,  29, -10,  44,  35,   2,  39,  21,  14,   1,
          7,  40,  35,  30,  42,  39,  11,  21,  14,  43,  -9,  40,  21,
         37,  46,  47,   8],
       [ -7,  36,  14,  45,   2,  30,  30,  -6,  43,  23,  48,  28,  45,
         26, -10,   5,  23,   7,   1,  47,  45,   6,  37,  29,  13,  31,
         28,  11,  38,  -4],
       [ -8,  47,   4,  -2,   3,   4,  30,  23,  22,  -7,  39,  26,  12,
         36,  -2,  43,  34,   3,  -4,  -7,  35,  38,  44,  14,  -7,   9,
         21,  32,   6,  -6],
       [ -3,  13,  12,  15,  15,  -6,  27,  24,  45,  -5,  -1,  21,  -7,
         11,  42,   7,  11,  11,   4,  -8,  -1,  46,  23,  21,  29,   6,
         -3,  22,  29,   0],
       [ 12,  29,  36,   1,   6,  19,   8,  15,  -7,  15,   3,  -1,  -9,
         46,  11,  24,   0,  45,  10,  32,  49,  -9,  48,  14,  18,  10,
        -10,   3,  -8,  -4],
       [ 49,  27,  30,   3,  39,  11,  12,  46,   4,  35,  41,  17,  39,
         26,  29,  -9,  49,  29,  10,  39,  47,   6,

In [83]:
month = ["Jan","Feb","March","April","May","June","July","August","Sep","Oct","Nov","Dec"]

In [85]:
for x in range(12):
    print(f"{month[x]}")
    print("-"*10)
    print(f"min:{np.min(newweather[x,:])}")
    print(f"max:{np.max(newweather[x,:])}")
    print(f"25th percentile:{np.percentile(newweather[x,:],25)}")
    print(f"75th percentile:{np.percentile(newweather[x,:],75)}")
    print(f"average:{np.mean(newweather[x,:])}")
    print(f"median:{np.median(newweather[x,:])}")
    print("-"*30)
    print()

Jan
----------
min:-10
max:47
25th percentile:8.75
75th percentile:39.0
average:23.333333333333332
median:25.0
------------------------------

Feb
----------
min:-10
max:48
25th percentile:6.25
75th percentile:36.75
average:22.133333333333333
median:27.0
------------------------------

March
----------
min:-8
max:47
25th percentile:-0.75
75th percentile:33.5
average:16.066666666666666
median:13.0
------------------------------

April
----------
min:-8
max:46
25th percentile:-0.75
75th percentile:22.75
average:13.333333333333334
median:11.5
------------------------------

May
----------
min:-10
max:49
25th percentile:0.25
75th percentile:22.75
average:13.533333333333333
median:10.5
------------------------------

June
----------
min:-9
max:49
25th percentile:12.25
75th percentile:39.0
average:26.666666666666668
median:29.0
------------------------------

July
----------
min:-10
max:45
25th percentile:-1.0
75th percentile:29.75
average:14.4
median:16.5
------------------------------

Aug

14. Create a mask for your data, and filter out and print:
- the average temperature of the days where the temperature was below 10
- the average temperature of the days where the temperature was greater than 30

In [94]:
print(f"The average temperature of the days where the temperature was below 10 is: {np.average(newweather[newweather<10])}")

The average temperature of the days where the temperature was below 10 is: -1.3391304347826087


In [95]:
print(f"The average temperature of the days where the temperature was greater than 30 is: {np.average(newweather[newweather>30])}")

The average temperature of the days where the temperature was greater than 30 is: 40.34862385321101


15. Create a full 10 by 10 matrix with a number of your choosing and assign it to a variable. After printing that variables, unravel the matrix and assign the array to a new number.

In [97]:
mymatrix = np.full((10,10), 30)
mymatrix

array([[30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [105]:
mymatrix2 = mymatrix.ravel().copy()
mymatrix2[:]=5
mymatrix2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])